# Generated by Django 6.0.5 on 2026-05-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_record_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='normalized_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='normalized_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
