# Generated by Django 6.0.5 on 2026-05-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_record_normalized_date_record_normalized_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='suspicious_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
