# Generated by Django 6.0.5 on 2026-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_record_suspicious_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
